export const FETCH_MORE_RECIPES_STARTED = 'FETCH_MORE_RECIPES_STARTED';
export const FETCH_MORE_RECIPES_SUCCEEDED = 'FETCH_MORE_RECIPES_SUCCEEDED';

export const FETCH_RECIPES_STARTED = 'FETCH_RECIPES_STARTED';
export const FETCH_RECIPES_SUCCEEDED = 'FETCH_RECIPES_SUCCEEDED';
export const FETCH_RECIPES_FAILED = 'FETCH_RECIPES_FAILED';

export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';

export const CHECKBOX_CHANGED = 'CHECKBOX_CHANGED';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_STARTED = 'REGISTER_STARTED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const POST_RECIPE_STARTED = 'POST_RECIPE_STARTED';
export const POST_RECIPE_FAILED = 'POST_RECIPE_FAILED';
export const POST_RECIPE_SUCCEEDED = 'POST_RECIPE_SUCCEEDED';
